spring:
  application:
    name: test
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  main:
    allow-circular-references: false

mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mybatis-xml-fast-develop-single-example-mapper/*.xml

logging:
  level:
    java.sql: debug
    javax.sql: debug
    com.test.mapper: debug