services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=root
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=0cf55b87b8
    ports:
      - "1433:1433"
  postgres:
    image: postgres:latest
    container_name: postgres-latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  mysql:
    image: mysql:8
    container_name: mysql-8
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"